/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CallBackQueryString {
  code: string;
  state: string;
}

export const callBackQueryStringSchema: Object = {
  title: "callBackQueryString",
  type: "object",
  properties: {
    code: {
      type: "string",
    },
    state: {
      type: "string",
    },
  },
  additionalProperties: false,
  required: [
    "code",
    "state",
  ],
  id: "CallBackQueryString",
};

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CallBackResponse {
  status: "SUCCESS" | "FAILED";
  data: {
    username: string;
    image?: string;
    name: string;
  };
}

export const callBackResponseSchema: Object = {
  title: "callBackResponse",
  type: "object",
  properties: {
    status: {
      type: "string",
      enum: [
        "SUCCESS",
        "FAILED",
      ],
    },
    data: {
      type: "object",
      properties: {
        username: {
          type: "string",
        },
        image: {
          type: "string",
        },
        name: {
          type: "string",
        },
      },
      additionalProperties: false,
      required: [
        "username",
        "name",
      ],
    },
  },
  additionalProperties: false,
  required: [
    "status",
    "data",
  ],
  id: "CallBackResponse",
};

/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GetUrlResponse {
  status: "SUCCESS" | "FAILED";
  data: {
    url: string;
    state: string;
    codeVerifier: string;
  };
}

export const getUrlResponseSchema: Object = {
  title: "getUrlResponse",
  type: "object",
  properties: {
    status: {
      type: "string",
      enum: [
        "SUCCESS",
        "FAILED",
      ],
    },
    data: {
      type: "object",
      properties: {
        url: {
          type: "string",
        },
        state: {
          type: "string",
        },
        codeVerifier: {
          type: "string",
        },
      },
      additionalProperties: false,
      required: [
        "url",
        "state",
        "codeVerifier",
      ],
    },
  },
  additionalProperties: false,
  required: [
    "status",
    "data",
  ],
  id: "GetUrlResponse",
};
